language: generic
matrix:
  include:
  - os: linux
    sudo: false
  - os: osx
env:
  global:
  - secure: HlbJvT0tBn/SM4uWh05ZNaajN6WBeBwmoe97O3lGeIPrZYYqzjD2OqyIZiH/Qxvj/GvqbT8mxeVPW+8kOWeCA/Mud944v5N3IwMS0tl7J0Xs0X68jveDi2D5062n47b3j2zPCgY0bmsGTaEwelQ4ZHaR4xc2OCTkIpkcOStUAYs=
  - secure: Z+i9DAetBkHpus+NnQllDpZ3Za7V4wpM2KKmnXy8n/1Ghcm6DdwgKqMQQdOiOaCtlEpZ28HcjVE9zariEbwzQ1kaI2vUVzNqCuFxczK87e0Zc9hs8KDRzrbsCkkXUj6G3YJBVhIsh8u1YOXLE5Yhr/ov2XlnfPMcXOfaugpAyAw=
  - secure: CN9Lsqo2UHxvqr883F0yVuFsn99COawF3+5me9cFBxrKmE2fm933NucRh7jnVDI98xa4SEcw4126S0lvmxB4O33JDXsZ5wYpeLgTqkaytS/R5mPKXkuwHDnqjuqtqAn+bIZmBmlkcW6zhuGG2yN/VecVBG8t++seQg6iN8sUrYI=
install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then which gsed || brew install gnu-sed; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then which gtimeout || brew install coreutils;
  fi
- bash --version
- awk --version
script: test/acceptance.sh
deploy:
  skip_cleanup: true
  provider: script
  script: website/.lanyon/vendor/bin/deploy
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
